"""complete_forensic_schema

Revision ID: ce38c853f27c
Revises: 
Create Date: 2026-09-10 17:55:23.922221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce38c853f27c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_name', sa.String(length=255), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('artifact_md5', sa.String(length=32), nullable=True),
    sa.Column('artifact_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('packet_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('completeness_percentage', sa.Float(), nullable=True),
    sa.Column('protocols_detected', sa.JSON(), nullable=True),
    sa.Column('streams_analyzed', sa.Integer(), nullable=True),
    sa.Column('posture_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('posture_details', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_index(op.f('ix_investigations_investigation_id'), 'investigations', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('deterministic_fallback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_agent_runs_investigation_id'), 'agent_runs', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_artifacts_artifact_id'), 'artifacts', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifacts_investigation_id'), 'artifacts', ['investigation_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_investigation_id'), 'audit_events', ['investigation_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('raw_artifact_ref', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=True),
    sa.Column('provenance_chain', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_hypothesis_id'), 'evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_evidence_type'), 'evidence', ['type'], unique=False)
    op.create_table('external_evidence',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=True),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('urls', sa.JSON(), nullable=True),
    sa.Column('titles', sa.JSON(), nullable=True),
    sa.Column('snippets', sa.JSON(), nullable=True),
    sa.Column('retrieval_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_index(op.f('ix_external_evidence_external_id'), 'external_evidence', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_evidence_hypothesis_id'), 'external_evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_external_evidence_investigation_id'), 'external_evidence', ['investigation_id'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_findings_finding_id'), 'findings', ['finding_id'], unique=False)
    op.create_index(op.f('ix_findings_investigation_id'), 'findings', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('forensic_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('server_ip', sa.String(length=64), nullable=True),
    sa.Column('client_port', sa.Integer(), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('tls_version', sa.String(length=32), nullable=True),
    sa.Column('cipher_suite', sa.String(length=128), nullable=True),
    sa.Column('sni', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_forensic_sessions_investigation_id'), 'forensic_sessions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_forensic_sessions_session_id'), 'forensic_sessions', ['session_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('hypothesis_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('refuting_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hypothesis_id')
    )
    op.create_index(op.f('ix_hypotheses_hypothesis_id'), 'hypotheses', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_investigation_id'), 'hypotheses', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('prediction_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('predicted_class', sa.String(length=64), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('class_confidence', sa.Float(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.Column('shap_attributions', sa.JSON(), nullable=True),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_ml_predictions_investigation_id'), 'ml_predictions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_prediction_id'), 'ml_predictions', ['prediction_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_investigation_id'), 'recommendations', ['investigation_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('stdout_summary', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_tool_executions_execution_id'), 'tool_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_investigation_id'), 'tool_executions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool'), 'tool_executions', ['tool'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('hypothesis', sa.String(length=255), nullable=True),
    sa.Column('selected_tool', sa.String(length=64), nullable=True),
    sa.Column('tool_arguments', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_investigation_id'), 'agent_steps', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_investigation_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_tool_executions_tool'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_investigation_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_execution_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_recommendations_investigation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_ml_predictions_prediction_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_investigation_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_investigation_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_hypothesis_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_forensic_sessions_session_id'), table_name='forensic_sessions')
    op.drop_index(op.f('ix_forensic_sessions_investigation_id'), table_name='forensic_sessions')
    op.drop_table('forensic_sessions')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_investigation_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_external_evidence_investigation_id'), table_name='external_evidence')
    op.drop_index(op.f('ix_external_evidence_hypothesis_id'), table_name='external_evidence')
    op.drop_index(op.f('ix_external_evidence_external_id'), table_name='external_evidence')
    op.drop_table('external_evidence')
    op.drop_index(op.f('ix_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_hypothesis_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_events_investigation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_artifacts_investigation_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_investigation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigation_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
